sudo: required
language: php
php:
  - '7.2'
env:
  global:
    - MYSQL_HOST=mariadb
    - MYSQL_DATABASE=travis
    - MYSQL_USER=travis
    - MYSQL_PASSWORD=travis
    - MYSQL_ROOT_PASSWORD=travis
services:
  - docker
install:
  - composer install --ignore-platform-reqs --prefer-dist --no-dev --optimize-autoloader
  - docker build -f docker/php/Dockerfile -t ligamanager/php .
before_script:
  - env | grep "^MYSQL_" > .env
script:
  - docker run -d --name mariadb --env-file .env mariadb
  - docker run --link mariadb dadarek/wait-for-dependencies mariadb:3306
  - docker run --link mariadb --env-file .env ligamanager/php bin/console.php orm:schema-tool:create
  - docker run --link mariadb --env-file .env ligamanager/php phpunit
after_script:
  - docker stop mariadb
  - docker rm mariadb