sudo: required
env:
  global:
    - MYSQL_HOST=mariadb
    - MYSQL_DATABASE=travis
    - MYSQL_USER=travis
    - MYSQL_PASSWORD=travis
    - MYSQL_ROOT_PASSWORD=travis
    - secure: FuqBOpeS5m0taRwqZGIX3e0lf5mxiGojcsahSnltIh3nFI9OrWingeWNiLvTTB8weAOqMzq4HHX+7qLGXva+F7m6r3BK9q6TuRmBk2GDGGEDJ98kCWZI8dFaDY2omarPjgi5jcpOV1ZfcJuly2aSPypolwGvTCoPaoiQGVtrEyg7oF030T0oq1mVHA5uMovwGAlTEdm/s1TH4JiWHsAMZh4SkAw/novbRJbh8ZJ+gDmLTi9FI9/2O/TLix14dSp01LiqTmz4Ww74QkZbGuQBvXeuLkcciaJVbPKWMDvSzI01ZKRD2mieC4IT4bI2o5J3oOH9+ZcJF8nlv3vLfOlA1aK/ecPLE9wjXFpffXr/y+jj0hj+7wkoJg8ppgkIuSHT0yduzynwCFgrU0sAgR4Z3xGPX9i4NL9JImH2SJAhPtU7QwEEvvOR0h6Oyzexuljtw8IVSG+ugL3L1Lf1g5YIOJECyDIYwCJPLq8YltyN/2uAcP2XwkPDTzmTU21leg1ZMxL6wwnc+iBxmDoVhQ8HqYE2bkXsvq7EVrARROGAjg9cc8HoHKa5fjZXqgZ8KiJrb6wyqgbgT1js+/gY2XZ5CbMFcfTw+mL9h80hIgY4Eqw+2y6aadZygZjLDALT1DV1KLl3T5bXB4OLaA5FJLeKOe9f+kaZP2Uwb6ZYxAjUKPw=
services:
  - docker
install:
  - sh docker/build-images.sh
before_script:
  - env | grep "^MYSQL_" > .env
script:
  - sh docker/run-tests.sh
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker push mklocke/liga-manager-api:latest