sudo: required
env:
  global:
    - DOCKER_USER=mklocke
    - DOCKER_REPO=mklocke/liga-manager-api
    - secure: DjqQeHbN1FNnNoHfeT9+e/unCPyZnOPsdS+sBOQW6kj2a1RNMkn4LBJn2+EL5bca8T70sM6xROxNPVhBob8UAI4k1MUJVqs7okJFZwDjmHFkHUEnlHt2O+ZROHqdwv0VGxsGy8SK6IaqLtzjoc8PMdcJxK9Uch5EwXw8xXeat+u50TtrUHymnoPFcqy/aZ3SbsTseiIqGUZECyiKGqxgp6YoRr7v9A/xtBX74TP/ojTaiet9JEpcBksUJZwMIlMHfu/EhB1j01ZyYuDbBr+KHDMKB1dWSmbEZeA1Jxxk6aGYrPQh2R827SaV4/SXjdhxYE0VL5o92p2PCWbN5Ev1qYPDCZM7Jm/tNEGIyPeXU0+TwK1LzxyENR+ljakfvqIWK6TQyohi1moi1iGwfekSd1HXLPe/CNOM4BF9LGGABfvXHwsfxLACx5Ygdcq3LfchKAs/GcqlQ8lumjgEc2YB8B2u0ogjLp01I3Wf+2vtgbJ/qGqnU5K2bhfdeXwkoFf/XbABzy2vwg5bVY2MH516kytqmmmYGjNgi3dBnxNCEgWdOSnM4f03/2ceylGuNxkx2Iy+zBDTKwvo69YCnPboN63iLmUBOuRay1fjjUqyoyQ2t6s3h8vMYasYnNeI0alXpbsCZ52avE3nAQTCzZfztmGw5HAGz7AQMskl7vjBjGo=
services:
  - docker
install:
  - export BRANCH=`if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi`
  - export TAG=`if [ "$BRANCH" == "master" ]; then echo "latest"; else echo $BRANCH ; fi`
script:
  - bash build.sh -c
after_success:
  - docker login -u $DOCKER_USER -p "$DOCKER_PASS"
  - docker push $DOCKER_REPO:$TAG