sudo: required
env:
  global:
    - MYSQL_HOST=mariadb
    - MYSQL_DATABASE=travis
    - MYSQL_USER=travis
    - MYSQL_PASSWORD=travis
    - MYSQL_ROOT_PASSWORD=travis
services:
  - docker
install:
  - sh docker/build-images.sh
before_script:
  - env | grep "^MYSQL_" > .env
script:
  - sh docker/run-tests.sh
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker push mklocke/liga-manager-api:latest