sudo: required
env:
  global:
    - MYSQL_HOST=mariadb
    - MYSQL_DATABASE=travis
    - MYSQL_USER=travis
    - MYSQL_PASSWORD=travis
    - MYSQL_ROOT_PASSWORD=travis
    - secure: "XECtLLclm0RhQIsb/PgvPipnrRpN/+JdEPoJ6mJko/ej8Ge/zkCd0DluosLcDBLfRjL4p60LTIXbDpCoAiiNg2tQTaEPPNpY2d56AHqd6gU3kgni0zjv/y70SVfi8+mm0mo5cKIwh3sr6Ny6Fwx4xTuloVADkQS0FTnbknaKnrwtkjXGUucVnbrQyf/+s4nT0g/fxyVWNn8yOsJyh3A3WIylQQAM69ual3Be1EHOiTe5XSTXJrwoJTLm3/DSAiudIbfIW1v4FVGN1ZZEvRe/FtjKrVUvkzv+TUy/Xa1vD4l6EZXioW73nkSs6i5+NQsFHsLAQGKbFnTXze5BJGjxaCJqo6q5fL4XhnvhJGv4gVkCCMdkesJh4ddfTO1BrKlDufIFtlfwFYUFF8xk59Mahkkdp03Nb1DDxc+YdS5xVQYKTH0xLS28ZQh8iqzEvlSuMHT5tWx0ZwEve081kFmgC9ISrQege8BRvEVRjVwf90HNufUDLX++h5KmkNaYijOLFATXFUozZau7GM2oE9kc+aSk+RKyXOHTtKl9RmJWJhEZ1KJ/eoZANwpbIouQAavj7NPiWB626AdRW0oYn4TNXvgmdOHPS639PwyeYmNvBXLpzDWOPbKKWkL0pewG4QwlQ4ClRPhQmiqsypjtsRNxC8Buxv9xMpUzAeMzYhXZ5+s="
services:
  - docker
install:
  - sh docker/build-images.sh
before_script:
  - env | grep "^MYSQL_" > .env
script:
  - sh docker/run-tests.sh
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker push mklocke/liga-manager-api:latest