sudo: required
env:
  global:
    - DOCKER_USER=mklocke
    - DOCKER_REPO=mklocke/liga-manager-api
    - secure: "Nr/qhO5IK1glrxhTnWcNl2vDTypr2NBWNottR/g911oRyG0M1/ZqQA8ozPxsu3yrB7KgCjgEWWKghrZJOsu14xrKzZ4aanbNOb8a05AKBf181vutP6VLlyFGfSr5rpO1ttOL3nSTKnTXV16jHAOALGNvU8/Fl06YucPwB+UXSvjCOTzqvmS1DYKvmBG7veTk7Kj8QrpJYtoBQ6p86uMuVU8sSqG54ZNC+WmTFL1ADixxKdmHVNTliG5qj9Qtwxpqj4rpYJtEHMlcZySWlUFtsGHAbhdQbBIss130jxiL4iGyaT7YmAHlGS5qyKOVEhjrAg1aU8lRu2YqYPNrxqeZT8LfqlUSopGhk+pGqer5mYa+qAuddvpmmAjsgFII+yJE2RF2pMY79Elta32K9Tg97KV/kF2m9Dbr7UCde5Du+WXYaSxoHrRQf8t9I/VPEQHquk9GmbZ0ys4ObGK+rgl/kbQZN+6eGeEBH4eLPa9jY0zdrWYGcVO1ORF8IoY6E+wzlxHzVS246PxoFchu1tnZ911L7HNVTJutjVbJJ0kcObCqumvOdD0cJekOMVxGwgYIK8Ex7uVmeEAtGuSIhr3ukAAU7LcR2p6lzZk3oxirx24wn8hBz5kkanQZ9eDApmaqnFUfdBBdcOV+iV5GRBV7nDA8ZuS86SQE3fvVB4R+hiM="
services:
  - docker
install:
  - export BRANCH=`if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi`
  - export TAG=`if [ "$BRANCH" == "master" ]; then echo "latest"; else echo $BRANCH ; fi`
script:
  - bash build.sh -c
after_success:
  - docker login -u $DOCKER_USER -p "$DOCKER_PASS"
  - docker push $DOCKER_REPO:$TAG