sudo: required
language: php
php:
  - '7.2'
env:
  global:
    - MYSQL_HOST=mariadb
    - MYSQL_DATABASE=travis
    - MYSQL_USER=travis
    - MYSQL_PASSWORD=travis
    - MYSQL_ROOT_PASSWORD=travis
services:
  - docker
install:
  - sh docker/build-images.sh
before_script:
  - env | grep "^MYSQL_" > .env
script:
  - sh docker/run-tests.sh