sudo: required
language: php
php:
  - '7.2'
services:
  - docker
before_install:
  - docker --version
  - echo "ENV GIT_SHA ${TRAVIS_COMMIT}" >> docker/php/Dockerfile
install:
  - composer install --ignore-platform-reqs --prefer-dist --no-dev --optimize-autoloader
  - docker build -f docker/php/Dockerfile -t ligamanager/php .
script:
  - docker run -d --name mariadb mariadb:10.2
  - docker run --link mariadb -e MYSQL_HOST=mariadb ligamanager/php phpunit
