version: '3'
services:
  php:
    image: $DOCKER_REPO:$TAG
    depends_on:
      - mariadb
      - redis
    env_file:
      - build.env

  mariadb:
    image: mariadb
    env_file:
      - build.env

  redis:
    image: redis:5-alpine
