version: '3'
services:
  php:
    image: mklocke/liga-manager-api:$TAG
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    depends_on:
      - mariadb
      - redis
    env_file:
      - build.env

  mariadb:
    image: mariadb:10.4
    env_file:
      - build.env

  redis:
    image: redis:5-alpine
