name: Docker Test
on: [push]
jobs:
  Docker-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: env
      - run: bash build.sh -c
