name: Docker Test
on: [push]
jobs:
  Docker-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build, Test & Publish
        run: bash build.sh -c
        env:
          ALLOW_TESTS: 1
          COVERALLS_RUN_LOCALLY: 1
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
